### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by Aakash1109** [netfirms/SimpleAndroidNeuralNetworkOCR#4]
FATAL EXCEPTION: dataLoader
                  Process: com.pranburiorchard.netfirms.simpleandroidocr, PID: 7330
                  org.neuroph.core.exceptions.NeurophException: Class not found while trying to read neural network from file!
                      at org.neuroph.core.NeuralNetwork.load(NeuralNetwork.java:638)
                      at com.pranburiorchard.netfirms.simpleandroidocr.customview.WritingView$1.run(WritingView.java:41)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.Logger
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:324)
                      at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:2258)
                      at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1641)
                      at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657)
                      at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1782)
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                      at java.io.ObjectInputStream.readFieldValues(ObjectInputStream.java:1113)
                      at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:454)
                      at org.neuroph.core.NeuralNetwork.readObject(NeuralNetwork.java:651)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1330)
                      at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
                      at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                      at org.neuroph.core.NeuralNetwork.load(NeuralNetwork.java:631)
                      at com.pranburiorchard.netfirms.simpleandroidocr.customview.WritingView$1.run(WritingView.java:41) 
                      at java.lang.Thread.run(Thread.java:818) 
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "ch.qos.logback.classic.Logger" on path: DexPathList[[zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/base.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.pranburiorchard.netfirms.simpleandroidocr-2/lib/arm64, /vendor/lib64, /system/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at java.lang.Class.classForName(Native Method) 
                      at java.lang.Class.forName(Class.java:324) 
                      at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:2258) 
                      at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1641) 
                      at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657) 
                      at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1782) 
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761) 
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983) 
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940) 
                      at java.io.ObjectInputStream.readFieldValues(ObjectInputStream.java:1113) 
                      at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:454) 
                      at org.neuroph.core.NeuralNetwork.readObject(NeuralNetwork.java:651) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1330) 
                      at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242) 
                      at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835) 
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761) 
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983) 
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940) 
                      at org.neuroph.core.NeuralNetwork.load(NeuralNetwork.java:631) 
                      at com.pranburiorchard.netfirms.simpleandroidocr.customview.WritingView$1.run(WritingView.java:41) 
                      at java.lang.Thread.run(Thread.java:818) 
                  	Suppressed: java.lang.ClassNotFoundException: ch.qos.logback.classic.Logger
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 23 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by Aakash1109** [comment]
### I found out the API is deprecated and so instead of load() which expects a string they have used createFromFile() which expects a path for m1.nnet please help!

**Comment by netfirms** [comment]
> ### I found out the API is deprecated and so instead of load() which expects a string they have used createFromFile() which expects a path for m1.nnet please help!

I've tried to run on emulator and it works fine. 
Can you try build and run on emulator first? may be it have something that relate to file systems.

**Comment by Aakash1109** [comment]
> > ### I found out the API is deprecated and so instead of load() which expects a string they have used createFromFile() which expects a path for m1.nnet please help!
> 
> I've tried to run on emulator and it works fine.
> Can you try build and run on emulator first? may be it have something that relate to file systems.

Yes I tried on Emulator as well it says the same runtime exception and after reading all the documentation here is the link you should see which states load() cannot be used anymore

[(http://neuroph.sourceforge.net/javadoc/org/neuroph/core/NeuralNetwork.html#load-java.lang.String-)]
